version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped
    environment:
      POSTGRES_USER: "lrjq"
      POSTGRES_PASSWORD: "lrjq"
      POSTGRES_DB: "queue"
      PGDATA: "/data/postgres"
    volumes:
    #   - ./db-data/:/var/lib/postgresql/data
        - ./.postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql

  queue:
    build:
      context: .
      target: development
    ports:
      - 8796:8796
    volumes:
      - ./:/app/
    environment:
      TEST_POSTGRES_CONN: postgres://lrjq:lrjq@postgres:5432/testdb
      POSTGRES_CONN_STR: postgres://lrjq:lrjq@postgres:5432/queue
      PORT: 8796
      LOG_LEVEL: DEBUG
