openapi: 3.0.0
info:
  title: My API
  version: 0.0.1
paths:
  /pkg/{pkgName}/lol:
    post:
      operationId: lol
      parameters:
      - name: pkgName
        in: path
        required: true
        schema:
          type: string
      - name: orderBy
        in: query
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              pattern: "^\\w{6}$"
      responses:
        default:
          description: ''
